version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
      # - rabbitmq

  postgres:
    # build: ./infrastructure/docker/postgres
    image: postgres:9-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   expose:
  #     - 5672

volumes:
  postgres:
